name: "tests"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  databricks_repo: "datarootsio/databricks-terraform"
  databricks_branch: "bugfix/content-state-validate"
jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: Get databricks provider dependency
        run: |
          rm -rf ${{ github.workspace }}/databricks-terraform
          git clone --depth 1 -b ${{ env.databricks_branch }} https://github.com/${{ env.databricks_repo }}.git ${{ github.workspace }}/databricks-terraform

      - name: Build databricks provider dependency
        run: |
          cd ${{ github.workspace }}/databricks-terraform
          go build -o ~/.terraform.d/plugins/terraform-provider-databricks
          cd -

      - name: "Checkout"
        uses: actions/checkout@master

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tflint
        run: docker run --rm -v $(pwd):/data -t wata727/tflint